FROM python:3.12

WORKDIR /app

# Install TA-Lib system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    make \
    libta-lib0 \
    ta-lib \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
