services:
  - type: web
    name: fastapi-app
    runtime: python
    plan: free  # Change this if using a paid plan
    region: oregon  # Adjust based on your needs
    buildCommand: |
      apt-get update && apt-get install -y build-essential ta-lib
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"  # Change to "3.10" if needed for TA-Lib compatibility
      - key: SECRET_KEY
        sync: false  # Set in Render's environment variables manually
